CREATE SCHEMA `library_db` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `manufacturers` (
  `id` BIGINT(10) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`));